//! Writing generated meshes into `assets/meshes/`.
//!
//! The sibling of [`crate::assets`], and it starts from the same rule — the
//! path is a pure function of the bytes, so two people who generate the same
//! mesh onto one share write identical files to an identical place and neither
//! can lose the other's work. What is different here is that **a mesh is not
//! reliably one file**, and that difference decides everything below.
//!
//! `docs/08-providers.md`: the OBJ result URL is a `.zip` of "mesh + `.mtl` +
//! texture maps". An `.obj` finds its material library through a `mtllib` line
//! holding a bare filename, and the `.mtl` finds its textures through `map_Kd`
//! lines holding bare filenames, all resolved relative to the mesh. Those names
//! are load-bearing strings inside the files. So the content-addressing that
//! works perfectly for an image — hash the bytes, rename the file after the
//! hash, shard it by its first two characters — is precisely wrong for a mesh:
//! it would rename every one of those files and scatter them into different
//! directories, and every reference would miss.
//!
//! The mesh would still load. It would load grey, with no material, and there
//! is no error to notice: the OBJ parser was not asked to open a file it could
//! not find, it was asked to open one whose name it read out of a line it
//! parsed fine. Nothing logs, nothing fails, and the first report is a person
//! saying the model looks wrong. That is the failure this module exists to make
//! impossible, and it is why the checks here refuse rather than do their best.
//!
//! Three rules, each the multi-file restatement of one of `assets.rs`':
//!
//! - **The directory is the unit.** [`wobu_core::asset::mesh_dir`] gives one
//!   mesh one folder; the mesh is `model.<ext>` and everything it references
//!   sits beside it under the name it was delivered with.
//! - **The hash covers the whole set, names included.** See [`hash_layout`].
//! - **A mesh that is already there is left alone — but only if it is whole.**
//!   Completeness is per file, because the way a mesh breaks on a share is one
//!   texture still in flight.

use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use wobu_core::asset::{MESH_STEM, mesh_dir, mesh_extra_path, mesh_file_name};

use crate::error::{Error, Result};
use crate::paths;

/// Where meshes live, relative to the project root.
pub const MESHES_DIR: &str = "assets/meshes";

/// One file on its way into the folder, borrowed from whatever produced it.
///
/// A name and bytes rather than `wobu_imagine::MeshFile`, and that is a
/// dependency direction rather than a preference: this crate owns the project
/// folder and knows nothing about providers, so a mesh generated by a backend
/// we have not written yet has to be storable through the same door. The app
/// crate, which depends on both, does the two-line mapping.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MeshPart<'a> {
    /// The name the file had where it came from — inside the archive, for the
    /// provider that prompted this.
    pub name: &'a str,
    pub bytes: &'a [u8],
}

impl<'a> MeshPart<'a> {
    pub fn new(name: &'a str, bytes: &'a [u8]) -> MeshPart<'a> {
        MeshPart { name, bytes }
    }
}

/// What an import did, and where the mesh ended up.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImportedMesh {
    /// Lowercase hex BLAKE3 of the whole stored set. See [`hash_layout`].
    pub hash: String,
    /// The directory holding this mesh and everything it references,
    /// project-relative and `/`-separated.
    pub dir: String,
    /// The mesh itself — the path to hand a viewer.
    pub rel_path: String,
    /// Every file in the set, project-relative, mesh first.
    ///
    /// The mesh alone would be a half-truth on a share: the sync client has to
    /// carry all of these or the model arrives grey.
    pub files: Vec<String>,
    /// The set's total size on disk.
    pub bytes: u64,
    /// True when every file was already present and whole, and nothing was
    /// written.
    pub deduped: bool,
}

/// Put a mesh and everything it references in the folder, or discover they are
/// already there.
///
/// The mesh is separated from its `extras` in the signature rather than passed
/// as one list with a convention about which entry is the mesh, because which
/// file is the mesh is the one thing that cannot be recovered from the set: an
/// `.obj` and its `.mtl` are both text, both named `model`, and picking the
/// wrong one is a viewer opening a material library as geometry. The caller
/// always knows; a positional rule would be the one fact worth carrying, left
/// implicit.
pub fn import(root: &Path, mesh: MeshPart<'_>, extras: &[MeshPart<'_>]) -> Result<ImportedMesh> {
    let laid_out = layout(mesh, extras)?;
    let hash = hash_layout(&laid_out);

    let dir_rel = mesh_dir(&hash);
    let dir = paths::from_rel_string(root, &dir_rel);

    // Whole, or not there at all. Checked before anything is staged because
    // this is the common case on a share — the second person to generate the
    // same mesh does no IO beyond a handful of `stat` calls.
    let deduped = laid_out.iter().all(|(name, bytes)| {
        matches!(fs::metadata(dir.join(rel_to_native(name))), Ok(meta) if meta.len() == bytes.len() as u64)
    });
    if !deduped {
        write_set(root, &dir, &laid_out)?;
    }

    // Joined by `wobu-core`, not with a `format!` here. A second spelling of
    // `assets/meshes/<ab>/<hash>/` is one edit away from a writer and a reader
    // disagreeing about where a mesh is.
    let files: Vec<String> = laid_out.iter().map(|(name, _)| mesh_extra_path(&hash, name)).collect();
    Ok(ImportedMesh {
        // The mesh is first in `laid_out` and stays first here, so `files[0]`
        // and `rel_path` cannot disagree.
        rel_path: files[0].clone(),
        bytes: laid_out.iter().map(|(_, bytes)| bytes.len() as u64).sum(),
        files,
        dir: dir_rel,
        hash,
        deduped,
    })
}

/// The mesh inside a mesh directory, if there is one.
///
/// Found by stem rather than by extension, which is what [`MESH_STEM`] buys:
/// the format is not knowable from the hash, and a reader that had to guess
/// between `.obj`, `.glb` and whatever a future provider returns would either
/// hold a list of extensions that goes stale or open the first file it saw —
/// and the first file it saw could easily be the `.mtl`.
pub fn locate(root: &Path, hash: &str) -> Option<PathBuf> {
    let dir = paths::from_rel_string(root, &mesh_dir(hash));
    fs::read_dir(dir)
        .ok()?
        .filter_map(std::result::Result::ok)
        .map(|entry| entry.path())
        .find(|path| path.is_file() && path.file_stem().is_some_and(|stem| stem == MESH_STEM))
}

/// Decide what every file is called inside the mesh's directory, mesh first.
///
/// Two things happen here, and both are about keeping references resolvable
/// rather than about tidiness:
///
/// **A shared leading directory is stripped from every name at once.** Archives
/// come both ways — everything at the root, or everything under one folder —
/// and stripping a prefix that all of them share moves them together, so every
/// file that was a sibling still is. Not stripping it would bury the mesh a
/// level down where [`mesh_path`] does not look for it.
///
/// **The mesh is renamed and nothing else is.** References point from the mesh
/// outwards and never back at it, so its own name is the one in the set that no
/// file depends on. That asymmetry is the whole design: a predictable name for
/// the file we have to find, and delivered names for the files that have to be
/// found.
fn layout<'a>(mesh: MeshPart<'a>, extras: &[MeshPart<'a>]) -> Result<Vec<(String, &'a [u8])>> {
    for part in std::iter::once(&mesh).chain(extras) {
        check_name(part.name)?;
    }

    let names: Vec<&str> = std::iter::once(mesh.name).chain(extras.iter().map(|e| e.name)).collect();
    let prefix = common_dir(&names);

    let mesh_name = &mesh.name[prefix..];
    // After stripping, the mesh has to sit at the root of its own directory —
    // otherwise renaming it to `model.<ext>` moves it away from the siblings it
    // names, and the `mtllib` line points at nothing. An archive shaped like
    // that is rare enough that refusing it beats writing a mesh that opens
    // grey.
    if mesh_name.contains('/') {
        return Err(Error::UnusableMesh(format!(
            "`{}` sits in a folder its own textures do not share, so nothing it \
             references would be beside it",
            mesh.name,
        )));
    }

    let ext = mesh_name.rsplit_once('.').map(|(_, ext)| ext.to_ascii_lowercase()).unwrap_or_default();
    // The stored name, not the delivered one — see `hash_layout` for why that
    // distinction has to hold all the way through. Asked of `wobu-core` rather
    // than spelled again here, so that this and `mesh_path` cannot disagree
    // about what the mesh ends up called.
    let stored_mesh = mesh_file_name(&ext);

    let mut out = Vec::with_capacity(extras.len() + 1);
    out.push((stored_mesh.clone(), mesh.bytes));
    for extra in extras {
        let name = extra.name[prefix..].to_owned();
        if name == stored_mesh {
            return Err(Error::UnusableMesh(format!(
                "`{}` would be written over the mesh itself",
                extra.name,
            )));
        }
        if out.iter().any(|(seen, _)| *seen == name) {
            return Err(Error::UnusableMesh(format!("`{name}` appears twice")));
        }
        out.push((name, extra.bytes));
    }
    Ok(out)
}

/// Refuse a name that must not reach the filesystem.
///
/// The names here came out of an archive downloaded from a third party, so this
/// is the boundary where a string someone else chose becomes a path we create.
/// `wobu-imagine`'s ZIP reader checks its own entries, and this checks them
/// again on purpose: that check protects that reader's callers, this one
/// protects the project folder, and the day a second mesh backend arrives it
/// will not have gone through the first.
fn check_name(name: &str) -> Result<()> {
    let refuse = |why: &str| Err(Error::UnusableMesh(format!("`{name}` {why}")));
    if name.is_empty() {
        return Err(Error::UnusableMesh("a file in it has no name".to_owned()));
    }
    // A backslash is a separator on Windows and an ordinary character
    // elsewhere, so the same archive would lay out two different ways.
    if name.contains('\\') {
        return refuse("contains a backslash, which is a separator on one platform and not another");
    }
    if name.starts_with('/') {
        return refuse("is an absolute path");
    }
    // `:` is a drive letter and an alternate-data-stream marker on Windows.
    if name.contains(':') {
        return refuse("contains a colon");
    }
    if name.split('/').any(|part| part.is_empty() || part == "." || part == "..") {
        return refuse("would escape the mesh's own folder");
    }
    Ok(())
}

/// The byte length of the longest `/`-terminated prefix every name shares.
///
/// Whole path components only: `textures/` and `textures_hi/` share five
/// characters and no directory at all, and treating that as a prefix would
/// slice both names into nonsense.
fn common_dir(names: &[&str]) -> usize {
    let Some((first, rest)) = names.split_first() else {
        return 0;
    };
    let mut prefix = 0;
    for (at, _) in first.match_indices('/') {
        let candidate = at + 1;
        if rest.iter().all(|name| name.as_bytes().starts_with(&first.as_bytes()[..candidate])) {
            prefix = candidate;
        } else {
            break;
        }
    }
    prefix
}

/// The hash of a whole mesh, over the layout it will have on disk.
///
/// Three decisions, each of which is a way this could quietly go wrong:
///
/// **Every file, not just the mesh.** Hashing the `.obj` alone would give one
/// address to two generations that share geometry and differ in their textures,
/// and the second import would find a complete directory, report a dedup, and
/// write nothing — leaving the first generation's textures on the second's
/// mesh. A silent, plausible, wrong result.
///
/// **Names as well as bytes.** The names are content: a `mtllib` line names a
/// file, so the same bytes under different names are a different mesh, and one
/// of the two versions loads grey.
///
/// **The stored name, and sorted.** The address has to be a function of what
/// lands on disk rather than of what arrived, or the same archive delivered as
/// `out/mesh.obj` and as `model.obj` would take two addresses while producing
/// byte-identical directories — and the conflict-free claim rests on exactly
/// that not happening. Sorting removes archive ordering for the same reason.
///
/// Lengths are written before both name and bytes so that no two different sets
/// can be fed to the hasher as the same stream.
fn hash_layout(files: &[(String, &[u8])]) -> String {
    let mut sorted: Vec<&(String, &[u8])> = files.iter().collect();
    sorted.sort_by(|a, b| a.0.cmp(&b.0));

    let mut hasher = blake3::Hasher::new();
    for (name, bytes) in sorted {
        hasher.update(&(name.len() as u64).to_le_bytes());
        hasher.update(name.as_bytes());
        hasher.update(&(bytes.len() as u64).to_le_bytes());
        hasher.update(bytes);
    }
    hasher.finalize().to_hex().to_string()
}

/// Get the whole set onto disk without a reader ever seeing part of one.
///
/// Staged into `.wobu/tmp` and renamed, exactly as [`crate::assets`] does, but
/// the unit is the directory: a whole mesh appears at once, so a viewer opening
/// it either finds everything or finds nothing, and never finds an `.obj` whose
/// textures are still in flight. That is the case a per-file loop cannot give
/// us, and it is the common one — a mesh is the one asset large enough that the
/// window is wide.
///
/// The fallback exists because a directory rename only works onto a target that
/// is absent or empty. When one is already there, the mesh is present but not
/// whole — a half-synced copy, or an interrupted earlier import — and the
/// repair has to go file by file into the directory a reader may already be
/// holding open.
fn write_set(root: &Path, dir: &Path, files: &[(String, &[u8])]) -> Result<()> {
    let tmp_root = root.join(".wobu").join("tmp");
    paths::ensure_dir(&tmp_root)?;
    let staged = tmp_root.join(format!("{}.part", wobu_core::new_id()));

    let result = stage_all(&staged, files).and_then(|()| {
        if let Some(parent) = dir.parent() {
            paths::ensure_dir(parent)?;
        }
        match fs::rename(&staged, dir) {
            Ok(()) => Ok(()),
            // Something is already there. Repair it in place rather than
            // removing it first: a reader may have the old files open, and
            // every byte we are about to write is a byte it should have.
            Err(_) if dir.exists() => repair(dir, &staged, files),
            Err(e) => Err(Error::io(dir, e)),
        }
    });

    // Whatever happened, leave no litter — the staging directory survives a
    // successful rename only in the repair case.
    let _ = fs::remove_dir_all(&staged);
    result
}

fn stage_all(staged: &Path, files: &[(String, &[u8])]) -> Result<()> {
    paths::ensure_dir(staged)?;
    for (name, bytes) in files {
        let path = staged.join(rel_to_native(name));
        if let Some(parent) = path.parent() {
            paths::ensure_dir(parent)?;
        }
        let mut f = fs::File::create(&path).map_err(|e| Error::io(&path, e))?;
        f.write_all(bytes).map_err(|e| Error::io(&path, e))?;
        // Without this, a crash between the rename and the flush leaves
        // correctly-named files full of zeroes — which for a texture is a
        // black surface rather than a missing one.
        f.sync_all().map_err(|e| Error::io(&path, e))?;
    }
    Ok(())
}

/// Move the staged files into an existing directory one at a time, replacing
/// only what is missing or the wrong size.
fn repair(dir: &Path, staged: &Path, files: &[(String, &[u8])]) -> Result<()> {
    for (name, bytes) in files {
        let native = rel_to_native(name);
        let target = dir.join(&native);
        if matches!(fs::metadata(&target), Ok(meta) if meta.len() == bytes.len() as u64) {
            continue;
        }
        if let Some(parent) = target.parent() {
            paths::ensure_dir(parent)?;
        }
        fs::rename(staged.join(&native), &target).map_err(|e| Error::io(&target, e))?;
    }
    Ok(())
}

/// A stored name is always `/`-separated; the filesystem may not be.
fn rel_to_native(name: &str) -> PathBuf {
    name.split('/').fold(PathBuf::new(), |path, part| path.join(part))
}

#[cfg(test)]
mod tests {
    use wobu_core::asset::mesh_path;

    use super::*;

    /// The archive `docs/08-providers.md` describes: an OBJ, its material
    /// library, and a texture the library names.
    fn obj_set() -> (Vec<u8>, Vec<u8>, Vec<u8>) {
        (
            b"mtllib model.mtl\nv 0 0 0\n".to_vec(),
            b"newmtl m\nmap_Kd texture_0.png\n".to_vec(),
            vec![0x89, b'P', b'N', b'G', 1, 2, 3],
        )
    }

    fn import_obj(root: &Path) -> Result<ImportedMesh> {
        let (obj, mtl, png) = obj_set();
        import(
            root,
            MeshPart::new("model.obj", &obj),
            &[MeshPart::new("model.mtl", &mtl), MeshPart::new("texture_0.png", &png)],
        )
    }

    #[test]
    fn an_obj_lands_beside_the_files_it_names() {
        // The whole point. `mtllib model.mtl` and `map_Kd texture_0.png` are
        // resolved relative to the mesh, so all three have to share a parent
        // and keep the names written inside the files.
        let dir = tempfile::tempdir().unwrap();
        let out = import_obj(dir.path()).unwrap();

        assert!(out.rel_path.ends_with("/model.obj"), "{}", out.rel_path);
        assert_eq!(out.dir, format!("assets/meshes/{}/{}", &out.hash[..2], out.hash));
        assert_eq!(
            out.files,
            [
                format!("{}/model.obj", out.dir),
                format!("{}/model.mtl", out.dir),
                format!("{}/texture_0.png", out.dir),
            ],
        );
        for rel in &out.files {
            assert!(dir.path().join(rel).is_file(), "{rel} was not written");
        }
        assert!(!out.deduped);
        assert_eq!(out.bytes, 25 + 30 + 7);
    }

    #[test]
    fn a_glb_gets_the_same_directory_a_multi_file_mesh_gets() {
        // No branch on format. A layout that gave self-contained meshes a flat
        // file would put the multi-file case — the one whose breakage is
        // silent — on the path that is exercised least.
        let dir = tempfile::tempdir().unwrap();
        let glb = b"glTF____".to_vec();
        let out = import(dir.path(), MeshPart::new("model.glb", &glb), &[]).unwrap();

        assert_eq!(out.rel_path, format!("{}/model.glb", out.dir));
        assert_eq!(out.files.len(), 1);
        assert!(dir.path().join(&out.rel_path).is_file());
    }

    #[test]
    fn the_extension_is_the_meshs_own_and_never_glb_by_default() {
        // The bug that started this: `mesh_path` hardcoded `.glb`, and the
        // provider returns an OBJ. A `.glb` full of OBJ text is refused by
        // every viewer, and its name says the viewer is at fault.
        let dir = tempfile::tempdir().unwrap();
        for (name, ext) in [("model.obj", "obj"), ("scene.gltf", "gltf"), ("m.FBX", "fbx")] {
            let bytes = name.as_bytes();
            let out = import(dir.path(), MeshPart::new(name, bytes), &[]).unwrap();
            assert!(out.rel_path.ends_with(&format!("/model.{ext}")), "{}", out.rel_path);
        }
    }

    #[test]
    fn a_texture_changing_changes_the_address() {
        // Hashing only the mesh would give these two one directory. The second
        // import would find it complete, report a dedup and write nothing —
        // leaving the first mesh's textures on the second mesh, with no error
        // and a picture that looks almost right.
        let dir = tempfile::tempdir().unwrap();
        let (obj, mtl, png) = obj_set();
        let other_png = vec![0x89, b'P', b'N', b'G', 9, 9, 9];

        let first = import(
            dir.path(),
            MeshPart::new("model.obj", &obj),
            &[MeshPart::new("model.mtl", &mtl), MeshPart::new("texture_0.png", &png)],
        )
        .unwrap();
        let second = import(
            dir.path(),
            MeshPart::new("model.obj", &obj),
            &[MeshPart::new("model.mtl", &mtl), MeshPart::new("texture_0.png", &other_png)],
        )
        .unwrap();

        assert_ne!(first.hash, second.hash, "same geometry, different textures, one address");
        assert!(!second.deduped);
        assert_eq!(fs::read(dir.path().join(&first.files[2])).unwrap(), png);
        assert_eq!(fs::read(dir.path().join(&second.files[2])).unwrap(), other_png);
    }

    #[test]
    fn renaming_a_texture_changes_the_address_though_no_byte_did() {
        // The names are content — `map_Kd` names a file — so two sets that
        // differ only in what a texture is called are two different meshes, and
        // exactly one of them loads.
        let dir = tempfile::tempdir().unwrap();
        let (obj, mtl, png) = obj_set();
        let named = |texture: &str| {
            import(
                dir.path(),
                MeshPart::new("model.obj", &obj),
                &[MeshPart::new("model.mtl", &mtl), MeshPart::new(texture, &png)],
            )
            .unwrap()
            .hash
        };
        assert_ne!(named("texture_0.png"), named("Texture_0.png"));
    }

    #[test]
    fn the_address_follows_the_stored_layout_and_not_the_delivered_one() {
        // Two archives that produce byte-identical directories must produce one
        // directory. If they did not, the share would hold two copies of one
        // mesh and the conflict-free claim would cover the bytes but not the
        // folder.
        let dir = tempfile::tempdir().unwrap();
        let (obj, mtl, png) = obj_set();

        let flat = import(
            dir.path(),
            MeshPart::new("model.obj", &obj),
            &[MeshPart::new("model.mtl", &mtl), MeshPart::new("texture_0.png", &png)],
        )
        .unwrap();
        // The same three files, delivered under a folder and with the mesh
        // named something else.
        let nested = import(
            dir.path(),
            MeshPart::new("out/hunyuan_result.obj", &obj),
            &[MeshPart::new("out/model.mtl", &mtl), MeshPart::new("out/texture_0.png", &png)],
        )
        .unwrap();

        assert_eq!(flat.hash, nested.hash);
        assert_eq!(flat.files, nested.files);
        assert!(nested.deduped, "the second import had nothing left to write");
    }

    #[test]
    fn a_shared_folder_is_stripped_from_every_name_together() {
        // Moving them all keeps them siblings, which is what the references
        // need. Stripping it from some and not others would be the grey mesh.
        let dir = tempfile::tempdir().unwrap();
        let (obj, mtl, png) = obj_set();
        let out = import(
            dir.path(),
            MeshPart::new("mesh/model.obj", &obj),
            &[
                MeshPart::new("mesh/model.mtl", &mtl),
                MeshPart::new("mesh/maps/texture_0.png", &png),
            ],
        )
        .unwrap();

        assert_eq!(out.rel_path, format!("{}/model.obj", out.dir));
        // `maps/` is *not* stripped — it is not shared, and the `.mtl` names
        // the texture as `maps/texture_0.png`.
        assert_eq!(out.files[2], format!("{}/maps/texture_0.png", out.dir));
        assert!(dir.path().join(&out.files[2]).is_file());
    }

    #[test]
    fn a_partial_prefix_is_not_mistaken_for_a_shared_folder() {
        // `textures/` and `textures_hi/` share eight characters and no
        // directory. Slicing on the character count would cut both names into
        // nonsense.
        assert_eq!(common_dir(&["textures/a.png", "textures_hi/b.png"]), 0);
        assert_eq!(common_dir(&["out/a.obj", "out/b.mtl"]), 4);
        assert_eq!(common_dir(&["out/deep/a.obj", "out/deep/b.mtl"]), 9);
        assert_eq!(common_dir(&["a.obj", "b.mtl"]), 0);
        assert_eq!(common_dir(&["out/a.obj"]), 4, "a lone mesh has nothing to stay beside");
    }

    #[test]
    fn a_complete_mesh_is_left_alone_and_a_broken_one_is_repaired() {
        // A truncated texture is what a sync client copying a large mesh in
        // looks like from here. Treating a short file as a dedup hit would
        // leave it truncated forever, and a truncated texture is a surface that
        // renders black rather than one that reports a problem.
        let dir = tempfile::tempdir().unwrap();
        let first = import_obj(dir.path()).unwrap();

        let again = import_obj(dir.path()).unwrap();
        assert!(again.deduped);
        assert_eq!(again.files, first.files);

        let texture = dir.path().join(&first.files[2]);
        fs::write(&texture, b"xx").unwrap();
        let repaired = import_obj(dir.path()).unwrap();
        assert!(!repaired.deduped);
        assert_eq!(fs::read(&texture).unwrap(), obj_set().2);
    }

    #[test]
    fn a_missing_sibling_is_restored_without_disturbing_the_mesh() {
        // The dedup check is per file for this reason: the mesh being present
        // says nothing about whether the textures made it.
        let dir = tempfile::tempdir().unwrap();
        let out = import_obj(dir.path()).unwrap();
        fs::remove_file(dir.path().join(&out.files[1])).unwrap();

        let repaired = import_obj(dir.path()).unwrap();
        assert!(!repaired.deduped);
        assert_eq!(fs::read(dir.path().join(&out.files[1])).unwrap(), obj_set().1);
        assert_eq!(fs::read(dir.path().join(&out.files[0])).unwrap(), obj_set().0);
    }

    #[test]
    fn a_name_that_would_escape_the_folder_is_refused() {
        // These names come out of a `.zip` downloaded from a third party, so
        // this is where a string somebody else chose becomes a path we create.
        let dir = tempfile::tempdir().unwrap();
        let bytes = b"v 0 0 0\n";
        for bad in ["../escape.png", "/etc/passwd", "C:/windows", "sub/../../x", "a\\b.png", ""] {
            let result =
                import(dir.path(), MeshPart::new("model.obj", bytes), &[MeshPart::new(bad, bytes)]);
            assert!(matches!(result, Err(Error::UnusableMesh(_))), "`{bad}` was accepted");
        }
        assert!(!dir.path().join("assets").exists(), "nothing should have been written");
    }

    #[test]
    fn an_extra_that_would_overwrite_the_mesh_is_refused() {
        // The mesh is renamed to `model.<ext>` and the extras are not, so an
        // extra already called that would land on top of it — and the file left
        // behind would be a `.mtl` that a viewer opens as geometry.
        let dir = tempfile::tempdir().unwrap();
        let bytes = b"v 0 0 0\n";
        let result = import(
            dir.path(),
            MeshPart::new("hunyuan.obj", bytes),
            &[MeshPart::new("model.obj", b"newmtl m\n")],
        );
        assert!(matches!(result, Err(Error::UnusableMesh(_))), "{result:?}");
    }

    #[test]
    fn a_mesh_that_cannot_sit_beside_its_own_textures_is_refused_rather_than_written() {
        // No shared folder to strip, and the mesh is inside one anyway — so
        // moving it to where `mesh_path` expects it separates it from the files
        // it names. Writing it would produce a grey mesh; refusing says so
        // while somebody can still act on it.
        let dir = tempfile::tempdir().unwrap();
        let bytes = b"mtllib model.mtl\n";
        let result = import(
            dir.path(),
            MeshPart::new("out/model.obj", bytes),
            &[MeshPart::new("textures/wood.png", b"png")],
        );
        assert!(matches!(result, Err(Error::UnusableMesh(_))), "{result:?}");
    }

    #[test]
    fn the_mesh_is_found_again_without_knowing_its_format() {
        // A reader has the hash and nothing else — the format is not recoverable
        // from it. Finding the mesh by stem is what makes `model.<ext>` worth
        // having, and it must not return the `.mtl`.
        let dir = tempfile::tempdir().unwrap();
        let out = import_obj(dir.path()).unwrap();

        let found = locate(dir.path(), &out.hash).expect("the mesh is there");
        assert_eq!(found, dir.path().join(&out.rel_path));
        assert_eq!(found.extension().unwrap(), "obj");
        assert!(locate(dir.path(), &"f".repeat(64)).is_none());
    }

    #[test]
    fn staging_never_leaves_litter_behind() {
        let dir = tempfile::tempdir().unwrap();
        import_obj(dir.path()).unwrap();
        // And again, to exercise the repair path's cleanup too.
        let out = import_obj(dir.path()).unwrap();
        fs::remove_file(dir.path().join(&out.files[2])).unwrap();
        import_obj(dir.path()).unwrap();

        let leftovers: Vec<_> = fs::read_dir(dir.path().join(".wobu/tmp")).unwrap().collect();
        assert!(leftovers.is_empty(), "staging dir should be empty after an import");
    }

    #[test]
    fn a_mesh_directory_is_never_observed_half_written() {
        // The reason the unit is a directory rename rather than a loop of file
        // renames: a viewer that opened the folder between two writes would get
        // an `.obj` whose textures do not exist yet, which is the grey mesh
        // arriving through the front door.
        let dir = tempfile::tempdir().unwrap();
        let (obj, mtl, png) = obj_set();
        let laid_out = layout(
            MeshPart::new("model.obj", &obj),
            &[MeshPart::new("model.mtl", &mtl), MeshPart::new("texture_0.png", &png)],
        )
        .unwrap();
        let hash = hash_layout(&laid_out);
        let target = paths::from_rel_string(dir.path(), &mesh_dir(&hash));

        assert!(!target.exists());
        write_set(dir.path(), &target, &laid_out).unwrap();
        // Nothing created the directory before it was complete: it arrived
        // whole, by rename.
        assert_eq!(fs::read_dir(&target).unwrap().count(), 3);
    }

    #[test]
    fn the_path_the_core_computes_is_the_path_that_gets_written() {
        // `wobu-core` states the layout and this module has to be the thing
        // that obeys it — two independent spellings of `assets/meshes/ab/hash`
        // would be one edit away from a reader looking where nothing is.
        let dir = tempfile::tempdir().unwrap();
        let out = import_obj(dir.path()).unwrap();

        assert_eq!(out.dir, mesh_dir(&out.hash));
        assert_eq!(out.rel_path, mesh_path(&out.hash, "obj"));
        assert_eq!(out.files[1], mesh_extra_path(&out.hash, "model.mtl"));
        assert!(out.dir.starts_with(MESHES_DIR));
    }
}
